apiVersion: v1
kind: Namespace
metadata:
  name: team-c
  labels:
    tenant: team-c
    platform.io/managed-by: gitops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
